name: test build on multiple python versions

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: build theme
    strategy:
      fail-fast: false
      # matrix:
      #   python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Setup Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip setuptools
      #     python -m pip install .
      - name: Build Themes
        run: |
          uv run mkdocs build -v --strict
